services:
  backend:
    build: backend
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
  frontend:
    build: frontend
    command: npm run dev -- --host --watch
    volumes:
      - ./frontend:/app
      - "/app/node_modules"
    ports:
      - "3000:3000"
      - "5173:5173"
    env_file:
      - frontend/.env
